name:                min-max-pqueue
version:             0.1.0.0
github:              "zliu41/min-max-pqueue"
license:             BSD3
author:              "Ziyang Liu <free@cofree.io>"
maintainer:          "Ziyang Liu <free@cofree.io>"
copyright:           "2019 Ziyang Liu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Double-ended priority queues.
category:            Data Structures

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Min-max priority queues, also known as double-ended priority queues.

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.11 && < 0.7

library:
  source-dirs: src

benchmarks:
  benchmark:
    main: Main.hs
    source-dirs: benchmark
    dependencies:
      - criterion >= 1.4.1 && < 1.6
      - integer-logarithms >= 1.0.2.2 && < 1.1
      - min-max-pqueue
      - random >= 1.1 && < 1.2

tests:
  hedgehog:
    main:                Main.hs
    source-dirs:         test/hedgehog
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - hedgehog >= 0.6.1 && < 0.7
      - min-max-pqueue
