name:                min-max-pqueue
version:             0.1.0.0
github:              "zliu41/min-max-pqueue"
license:             BSD3
author:              "Ziyang Liu <free@cofree.io>"
maintainer:          "Ziyang Liu <free@cofree.io>"
copyright:           "2019 Ziyang Liu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zliu41/min-max-pqueue#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- integer-logarithms

library:
  source-dirs: src

benchmarks:
  benchmark:
    main: Main.hs
    source-dirs: benchmark
    dependencies:
      - deepseq
      - criterion
      - min-max-pqueue

tests:
  hedgehog:
    main:                Main.hs
    source-dirs:         test/hedgehog
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - hedgehog
      - min-max-pqueue
